### ISSUE TITLE
Should pushString return a sentinel slice?

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/ziglua#113]
`pub fn pushString(lua: *Lua, str: []const u8) [:0]const u8`. The docs say The string can contain any binary data, including embedded zeros. This should probably only return a `[]const u8`

**Comment by robbielyman** [comment]
I don't think `[:0]const u8` (or sentinel slices in general) have as an invariant that the sentinel is *not* present inside the body of the slice, just that the sentinel is the value at `slice.ptr[slice.len]`, so keeping this as a `[:0]const u8` is correct.

**Comment by natecraddock** [comment]
That makes sense, thanks for the clarification!
