### ISSUE TITLE
bug: Lua 5.1 API doesn't support `lua_yieldk` on `yield`

### ISSUE THREAD

**Issue by nikneym** [natecraddock/ziglua#14]
`lua_yieldk` function is not presented in Lua 5.1 API. Instead, `lua_yield` should be used. Also it's [stated](https://www.lua.org/manual/5.1/manual.html#lua_yield) in Lua manual that this function must be called as return expression.

**Comment by natecraddock** [comment]
Thanks for reporting this! It looks like I need to add a test for yield in the 5.1 wrapper. I'll get to this soon.

**Comment by natecraddock** [comment]
Thank you again for reporting! The issue was that I implemented the 5.1 API by copying my code for the 5.2 API which does use `lua_yieldk` (and `lua_yieldk` does not return). Let me know if there is anything else to help with in the future!
