### ISSUE TITLE
Errno compile error

### ISSUE THREAD

**Issue by ConnorRigby** [natecraddock/ziglua#21]
First of all thanks for this library, it saved me a ton of work!

i have an error compiling on Ubuntu - 
```
zig build-lib lua Debug native: error: error(compilation): clang failed with stderr: In file included from /home/connorrigby/workspace/connorrigby/coneboy/lib/ziglua/lib/lua-5.4/src/loslib.c:13:
In file included from /usr/include/errno.h:28:
In file included from /usr/include/bits/errno.h:26:
/usr/include/linux/errno.h:1:10: fatal error: 'asm/errno.h' file not found
```

I'm not really sure what's going on here, but this file seems to exist at `/include/asm-generic/errno.h` on my machine. Any pointers would be appreciated.

**Comment by ConnorRigby** [comment]
Update: solved this by `apt install gcc-multilib`.

**Comment by natecraddock** [comment]
Glad you figured it out!

Also, your Junkbot profile picture just sent me down memory lane, thank you for that 😄
