### ISSUE TITLE
Expose lua version to ziglua module and rename

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/ziglua#44]
The build option `version` to set the Lua version to build with should be exposed publicly in ziglua. This would allow users of ziglua to utilize conditional compilation and target multiple versions of lua.

With this, I think `version` isn't as clear as it could be. Especially with the recent Luau support and LuaJIT coming soon.

I propose renaming the option to `lang`. This would make usage look like this

Running tests
```
$ zig build test -Dlang=lua51
```

Dependency
```zig
const ziglua = b.dependency("ziglua", .{
    .target = target,
    .optimize = optimize,
    .lang = .luau,
});
```

Variable
```zig
if (ziglua.lang == .lua52) {
    // do something
}
```

**Comment by nurpax** [comment]
I agree that `lang` is better.  Could also be something like `flavor` or `lua_flavor`?  But lang is fine too.
