### ISSUE TITLE
Experimenting with Discord

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/ziglua#49]
I just added a Discord server link to the readme. [Here is another link](https://discord.gg/XpZqDFvAtK).

Maybe no one will join, but I figure it doesn't hurt to open up a second communication channel. Some people would be more likely to offer suggestions and feedback in a chat rather than opening an issue. Additionally, I hope people share cool things they build with Ziglua! This won't be a massive community, but I think it would be fun to have a small group discussing and sharing about cool Zig & Lua things.

I understand that there is some frustration in the open source world about using Discord for chats. This is an experiment and we will see if anyone joins.

**Comment by VisenDev** [comment]
@natecraddock Discord links automatically expire after a few days and you can't reenable them after they expire. When you create a new link, you need to make sure you set it to be permanent when you create it


<img width="432" alt="Screenshot 2024-01-20 at 9 23 13 AM" src="https://github.com/natecraddock/ziglua/assets/48253336/b6870068-46f3-43f4-af7c-2f8a62d7113c">

**Comment by natecraddock** [comment]
@VisenDev Is the link not working for you? I'm pretty sure I set it to never expire, but I can double check

**Comment by VisenDev** [comment]
>  Is the link not working for you?

Yes it says the link is invalid, I assumed it was expired. Perhaps I don't have permission to join for some reason?

**Comment by VisenDev** [comment]
Okay update, pasting the link into discord worked. Clicking it in my browser does not. Perhaps my adblocker/tracker-remover is breaking discord on the web

**Comment by natecraddock** [comment]
I've had issues joining other servers in the past, but I've never figured out exactly why. Looks like you figured it out though!

And I did confirm the link is set to never expire

**Comment by natecraddock** [comment]
It is pretty low traffic (understandably), but I really like the discord server as a second communication channel. I'll keep it :)
