### ISSUE TITLE
ZigLua Integration Error: Missing build.zig

### ISSUE THREAD

**Issue by hfghgakjd** [natecraddock/ziglua#61]
I added ziglua to my project according to the steps in the documentation. When I ran zig build run, I got the following:
``` zig
warning: FileNotFound: C:\Users\xxx\AppData\Local\zig\p\1220d2378a3a95e1f48b1a73b6a65af96d853cc17993c7aad61b6403f7fc611eed71\build.zig
error: FileNotFound
```

I looked under this directory and found that this is the source code of lua5.1. It is a dependency of build.zig.zon in ziglua. It is a C language project and does not have a build.zig file. How can I correctly integrate ziglua into my project?

The zig version I am using is 0.11.0.

**Comment by natecraddock** [comment]
Hey!

If you are using Zig 0.11.0, you will need to use an older version of Ziglua (the main branch currently supports 0.12.0-dev).

The most recent tagged release (0.2.0) supports Zig 0.11.0. You can use https://github.com/natecraddock/ziglua/archive/refs/tags/0.2.0.tar.gz as your package URL and that should resolve your issue!

**Comment by hfghgakjd** [comment]
Thank you so much for your help, it was incredibly helpful.😊
