### ISSUE TITLE
luajit: opening standard library fails

### ISSUE THREAD

**Issue by rockorager** [natecraddock/ziglua#64]
I know luajit support is in it's infancy but wanted to report that opening the standard libraries with it fails. I can swap out for 5.2 through 5.4 and `openLibs` or `openBase` work fine, but luajit fails:

```
/home/tim/.cache/zig/p/1220bc58b81db27e4a04f61703e0929fa3ec780a24698483aee1b349dee2cf9dd96a/src/lib.zig:2536:16: error: member function expected 1 argument(s), found 2
        try lua.loadFile(file_name, .binary_text);
            ~~~^~~~~~~~~
/home/tim/.cache/zig/p/1220bc58b81db27e4a04f61703e0929fa3ec780a24698483aee1b349dee2cf9dd96a/src/lib.zig:2652:5: note: function declared here
    fn loadFile51(lua: *Lua, file_name: [:0]const u8) !void {
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rockorager** [comment]
Note: this *does* happen with 5.1 also. My original text said 5.1 worked but I have verified it doesn't (same error).

**Comment by natecraddock** [comment]
Hey!

> that opening the standard libraries with it fails

Do you mean it segfaults/panics? I ran into this recently and I have a TODO comment to look into this more. If that's the case, I'll re-prioritize it and work on it sooner!

I think loadFile is one of the last functions that _doesn't_ have test coverage (I just never got around to adding it). So I'll make sure to get that tested!

**Comment by natecraddock** [comment]
Turns out the functions for opening libraries aren't meant to be called directly. Thanks again for reporting this!

I made a separate issue for loadFile: https://github.com/natecraddock/ziglua/issues/69
