### ISSUE TITLE
exportFn fails during semantic analysis

### ISSUE THREAD

**Issue by galli-miro** [natecraddock/ziglua#7]
I've tried to build a simple shared module using the `exportFn` in a `comptime` block. Using zig version `v0.11.0-dev.1638+7199d7c77` it fails with the following error:

```sh
/home/galli/repos/git.sr.ht/~hubidubi/river-lua/zig/lib/ziglua/src/ziglua-5.4/lib.zig:2021:13: error: TODO implement exporting arbitrary Value objects
    @export(declaration, .{ .name = "luaopen_" ++ name, .linkage = .Strong });
```

Since there is a TODO, I'm assuming this will be fixed at some point. But `git blame` tells me this TODO has been there for over 2 years, so who knows when that will happen.

build.zig:

```zig
const std = @import("std");
const ziglua = @import("lib/ziglua/build.zig");

pub fn build(b: *std.Build) void {
    // Standard release options allow the person running `zig build` to select
    // between Debug, ReleaseSafe, ReleaseFast, and ReleaseSmall.
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addSharedLibrary(.{
        .name = "test",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });
    lib.addModule("ziglua", ziglua.compileAndCreateModule(b, lib, .{ .shared = true }));
    lib.install();
}
```

main.zig:
```zig
const std = @import("std");
const ziglua = @import("ziglua");

usingnamespace ziglua;

fn hello(lua: *ziglua.Lua) i32 {
    _ = lua;
    std.debug.print("hello world\n", .{});
    return 1;
}

fn module(lua: *ziglua.Lua) i32 {
    var fns = [_]ziglua.FnReg{ .{ .name = "hello", .func = ziglua.wrap(hello) }, .{ .name = "", .func = null } };
    lua.newLib(fns[0..]);
    return 1;
}

comptime {
    ziglua.exportFn("hello", module);
}
```

My current fix is to do the exporting and wrapping by hand, but maybe I'm missing something:

```zig
export fn luaopen_module(L: *ziglua.LuaState) callconv(.C) c_int {
    var fns = [_]ziglua.FnReg{ .{ .name = "hello", .func = ziglua.wrap(hello) }, .{ .name = "", .func = null } };

    var lua = ziglua.Lua{ .state = L };
    lua.newLib(fns[0..]);

    return 1;
}
```

**Comment by natecraddock** [comment]
Hi! Thanks for reporting. I'll look into this later today. I haven't tested `exportFn()` with the newest version of Zig, and it has always been a bit messy.

**Comment by natecraddock** [comment]
I looked into this a bit more. This is indeed an issue with Zig. I might try fixing this in Zig (sounds like a small but fun challenge!)

Until then, your solution is the best way. I'll be sure to document this better.

Also, because this is Zig and we can know the size of arrays passed into functions, no need to end the `FnReg` array with a sentinel `.{ .name = "", .func = null }`.

**Comment by galli-miro** [comment]
Thanks for having a closer look and also for the tip with the array :)

**Comment by hryx** [comment]
There is now a work-in-progress PR that should address this: https://github.com/ziglang/zig/pull/14796

**Comment by natecraddock** [comment]
It looks like the PR only partially fixed this. There is no longer a semantic analysis error, and the code compiles. But the symbol is not found in the output object. I'll look again at this later

**Comment by natecraddock** [comment]
I found another Zig / Lua bindings project that seems to have solved this. Linking here to check on it later: https://github.com/truemedian/lunaro
