### ISSUE TITLE
Missing 'Content-Disposition' header for Content-Type=application/octet-stream

### ISSUE THREAD

**Issue by terrablue** [natecraddock/ziglua#74]
Hi, I'm getting the error in the title when running `zig build`. I didn't use `zig fetch` but added the URLs manually to my `build.zig.zon` (still on 0.11).

Do I need to upgrade to Zig master to use this?

**Comment by natecraddock** [comment]
Hey! ziglua does require Zig master right now. There is a tagged release for 0.11.0 though: https://github.com/natecraddock/ziglua/releases/tag/0.2.0

**Comment by terrablue** [comment]
Thanks! Upgrading to master did solve my issues!
