### ISSUE TITLE
luau loading script.

### ISSUE THREAD

**Issue by Lightnet** [natecraddock/ziglua#81]
I did try to use require or from import from luau. It crashed. I wonder if the file in script loading or not enable?

```
local foo require "foo"
```

I found LuaJIT and lua 5.-1 -5.4 is not working on 0.12.0. Found there compile option does not exist function I think.

Windows 10 64bit.

**Comment by natecraddock** [comment]
Sorry for the delay on this, I've been swamped the last month. I'll take a closer look later today / over the next few days and get back to you

**Comment by natecraddock** [comment]
Luau has a focus on sandboxing and does not support loading compiled modules with require. I'm not sure if there is anything for ziglua to handle here. If this is still an issue feel free to reipen.
