### ISSUE TITLE
Building DLLs to be used inside lua with `require`

### ISSUE THREAD

**Issue by Caue-Aron** [natecraddock/ziglua#83]
In the Lua C API we could write DLLs to be used as libraries in Lua, is there anything similar to such in ZigLua?

**Comment by natecraddock** [comment]
Yes, you can do this! I don't have a good example of how yet, but you should be able to use the `shared` option with the ziglua dependency to link as a shared library, and then use `ziglua.exportFn` to export a module function.

Thanks for this good reminder to get this documented

**Comment by Rolln-dev** [comment]
> In the Lua C API we could write DLLs to be used as libraries in Lua, is there anything similar to such in ZigLua?

Did you ever find a way to do this?

**Comment by Rolln-dev** [comment]
@Caue-Aron I did get this to work. See https://github.com/natecraddock/ziglua/issues/91#issuecomment-2305875459
