### ISSUE TITLE
Lua 5.1 - Does not have a luaL_checkversion function

### ISSUE THREAD

**Issue by Rolln-dev** [natecraddock/ziglua#91]
When creating the dependency using lua51
```zig
    const ziglua = b.dependency("ziglua", .{
        .target = target,
        .optimize = optimize,
        .lang = .lua51,
        .shared = true,
    });
```
build fails with
`
error: root struct of file 'cimport' has no member named 'luaL_checkversion_'
        return c.luaL_checkversion_(@ptrCast(lua), c.LUA_VERSION_NUM);
`

**Comment by natecraddock** [comment]
What code are you using this with? Lua 5.1 does not have a checkversion function https://www.lua.org/manual/5.1/manual.html

Simply depending on .lua51 shouldn't cause issues here

**Comment by Rolln-dev** [comment]
```lua
//src/root.zig
const ziglua = @import("ziglua");

fn zlo(lua: *ziglua.Lua) i32 {
    lua.newLib(&.{
        .{ .name = "add", .func = ziglua.wrap(add) },
    });
    return 1;
}

fn add(lua: *ziglua.Lua) i32 {
    const a = lua.toInteger(1) catch 0;
    const b = lua.toInteger(2) catch 0;
    lua.pushInteger(a + b);
    return 1;
}

comptime {
    _ = ziglua.exportFn("zlo", zlo);
}
```

**Comment by natecraddock** [comment]
Ah got it. So the newLib function doesn't exist in older versions of Lua and so is unsupported in Lua 5.1. The documentation for ziglua needs a lot of work still but I don't have a ton of time at the moment. Sorry about that.

You can use registerFns instead, see https://github.com/natecraddock/ziglua/issues/42 and https://natecraddock.github.io/ziglua/#ziglua.lib.Lua.registerFns

I do think that we could provide some sort of wrapper for newLib for older versions of Lua, I just haven't gotten around

**Comment by Rolln-dev** [comment]
Ok.  Thank you for the help. I have got it to work now.
```zig
//build.zig

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addSharedLibrary(.{
        .name = "mymodule",
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = .ReleaseSmall,
    });

    const ziglua = b.dependency("ziglua", .{
        .target = target,
        .optimize = optimize,
        .lang = .lua51,
        .shared = false,
    });

    lib.root_module.addImport("ziglua", ziglua.module("ziglua"));

    b.installArtifact(lib);
}
```
```zig
//src/root.zig

const std = @import("std");
const ziglua = @import("ziglua");


fn mymodule(lua: *ziglua.Lua) i32 {
    const fns = [_]ziglua.FnReg{ .{ .name = "hello", .func = ziglua.wrap(hello) }};
    lua.registerFns("mymodule", &fns);
    return 1;
}

fn hello(lua: *ziglua.Lua) i32 {
    _ = lua;
    std.debug.print("hello world\n", .{});
    return 1;
}

comptime {
    _ = ziglua.exportFn("mymodule", mymodule);
}
```
My particular version of Lua 5.1 is Win32 so also had to use an `x86-windows` build target.
```cmd
zig build -Dtarget=x86-windows
```

**Comment by Rolln-dev** [comment]
> Ah got it. So the newLib function doesn't exist in older versions of Lua and so is unsupported in Lua 5.1. The documentation for ziglua needs a lot of work still but I don't have a ton of time at the moment. Sorry about that.
> 
> You can use registerFns instead, see #42 and https://natecraddock.github.io/ziglua/#ziglua.lib.Lua.registerFns
> 
> I do think that we could provide some sort of wrapper for newLib for older versions of Lua, I just haven't gotten around

Ok.  You can close this issue if you'd like as I was able to get what I wanted working.
